apiVersion: v1
kind: Pod
metadata:
  name: broken-app
  labels:
    app: debug-demo
spec:
  containers:
  - name: web-server
    image: nginx:1.21
    ports:
    - containerPort: 80
    env:
    - name: CONFIG_FILE
      value: "/etc/config/app.conf"
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    - name: app-data
      mountPath: /var/app-data
  volumes:
  - name: config-volume
    configMap:
      name: app-config (issue)
  - name: app-data
    emptyDir: {}
  restartPolicy: Always
