apiVersion: v1
kind: Pod
metadata:
  name: problematic-app
spec:
  containers:
  - name: app-container
    image: busybox:1.35
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'App running...'; sleep 30; done"]
    env:
    - name: DEBUG_MODE
      value: "true"
